PROJECT_NAME="星通智数"

BACKEND_CORS_ORIGINS=${ZHISHU_CORS_ORIGINS}
SECRET_KEY=${ZHISHU_SECRET_KEY}

DEFAULT_PWD=${ZHISHU_DEFAULT_PWD}

LOG_LEVEL=${ZHISHU_LOG_LEVEL}
SQL_DEBUG=False

CACHE_TYPE=${ZHISHU_CACHE_TYPE}

MCP_ENABLED=${ZHISHU_MCP_ENABLED}

POSTGRES_SERVER=${ZHISHU_DB_HOST}
POSTGRES_PORT=${ZHISHU_DB_PORT}
POSTGRES_DB=${ZHISHU_DB_DB}
POSTGRES_USER=${ZHISHU_DB_USER}
POSTGRES_PASSWORD=${ZHISHU_DB_PASSWORD}

SERVER_IMAGE_HOST=${ZHISHU_SERVER_IMAGE_HOST}

ACCESS_TOKEN_EXPIRE_MINUTES=${ZHISHU_ACCESS_TOKEN_EXPIRE_MINUTES}

CONTEXT_PATH=${ZHISHU_CONTEXT_PATH}
